/**
 * PDF Letter Generator
 *
 * Renders a dispute letter (already produced by `generateDisputeLetter`) into
 * a clean, branded, print-ready PDF. The letter text is treated as plain text
 * with line wrapping. Output: a single PDF file ready to print and mail.
 *
 * One PDF per (creditor × bureau × round) combination.
 */

import jsPDF from "jspdf";

export type PdfLetterMeta = {
  letterText: string;
  creditor: string;
  bureau: string;
  round: number;
  filename?: string;
};

const GOLD = "#e4b64c";
const DARK = "#0a0a0e";
const MARGIN = 0.75; // inches
const LINE_HEIGHT = 0.18;

export function generateLetterPdf(meta: PdfLetterMeta): jsPDF {
  const doc = new jsPDF({
    unit: "in",
    format: "letter",
    orientation: "portrait",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usableWidth = pageWidth - MARGIN * 2;

  // === Header band ===
  doc.setFillColor(DARK);
  doc.rect(0, 0, pageWidth, 0.55, "F");

  doc.setTextColor(GOLD);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("FLORIFYE", MARGIN, 0.36);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(228, 182, 76);
  doc.text("STRATEGIC CREDIT RESTORATION", MARGIN, 0.5);

  doc.setTextColor(228, 182, 76);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  const stampText = `DISPUTE LETTER · ROUND ${meta.round} · ${meta.bureau.toUpperCase()}`;
  const stampWidth = doc.getTextWidth(stampText);
  doc.text(stampText, pageWidth - MARGIN - stampWidth, 0.36);

  // Gold accent line under header
  doc.setDrawColor(GOLD);
  doc.setLineWidth(0.015);
  doc.line(MARGIN, 0.7, pageWidth - MARGIN, 0.7);

  // === Body text ===
  doc.setTextColor(20, 20, 20);
  doc.setFont("times", "normal");
  doc.setFontSize(11);

  const lines = doc.splitTextToSize(meta.letterText, usableWidth) as string[];

  let cursorY = 1.0;
  const bottomLimit = pageHeight - 0.9;

  for (const line of lines) {
    if (cursorY > bottomLimit) {
      addFooter(doc, pageWidth, pageHeight);
      doc.addPage();
      addPageHeader(doc, pageWidth, meta);
      cursorY = 1.0;
    }
    doc.text(line, MARGIN, cursorY);
    cursorY += LINE_HEIGHT;
  }

  // Final footer
  addFooter(doc, pageWidth, pageHeight);

  return doc;
}

function addPageHeader(doc: jsPDF, pageWidth: number, meta: PdfLetterMeta) {
  doc.setFillColor(DARK);
  doc.rect(0, 0, pageWidth, 0.55, "F");
  doc.setTextColor(GOLD);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("FLORIFYE", MARGIN, 0.36);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.text(
    `Round ${meta.round} · ${meta.bureau} · ${meta.creditor}`,
    pageWidth - MARGIN,
    0.36,
    { align: "right" }
  );
  doc.setDrawColor(GOLD);
  doc.setLineWidth(0.012);
  doc.line(MARGIN, 0.6, pageWidth - MARGIN, 0.6);
}

function addFooter(doc: jsPDF, pageWidth: number, pageHeight: number) {
  doc.setDrawColor(GOLD);
  doc.setLineWidth(0.01);
  doc.line(MARGIN, pageHeight - 0.6, pageWidth - MARGIN, pageHeight - 0.6);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 130);
  doc.text(
    "Generated by Phimindflow · Send via Certified Mail · Keep your receipt",
    pageWidth / 2,
    pageHeight - 0.4,
    { align: "center" }
  );
  doc.text(
    "FCRA · FDCPA · Metro 2 compliant request — does not constitute legal advice",
    pageWidth / 2,
    pageHeight - 0.25,
    { align: "center" }
  );
}

export function downloadLetterPdf(meta: PdfLetterMeta) {
  const doc = generateLetterPdf(meta);
  const safe = (s: string) =>
    s
      .replace(/[^a-z0-9-]+/gi, "-")
      .replace(/^-+|-+$/g, "")
      .toLowerCase();
  const filename =
    meta.filename ||
    `florifye-dispute-${safe(meta.creditor)}-${safe(meta.bureau)}-round${meta.round}.pdf`;
  doc.save(filename);
}

/**
 * Bundle multiple letters into a single multi-page PDF.
 * Each letter gets its own page(s); a divider page goes between groups.
 */
export function downloadLetterBundle(letters: PdfLetterMeta[], bundleName = "florifye-dispute-bundle") {
  if (letters.length === 0) return;

  const doc = new jsPDF({ unit: "in", format: "letter", orientation: "portrait" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usableWidth = pageWidth - MARGIN * 2;

  letters.forEach((letter, idx) => {
    if (idx > 0) doc.addPage();

    // Header
    doc.setFillColor(DARK);
    doc.rect(0, 0, pageWidth, 0.55, "F");
    doc.setTextColor(GOLD);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("FLORIFYE", MARGIN, 0.36);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text("STRATEGIC CREDIT RESTORATION", MARGIN, 0.5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    const stamp = `LETTER ${idx + 1} OF ${letters.length} · ROUND ${letter.round} · ${letter.bureau.toUpperCase()}`;
    const w = doc.getTextWidth(stamp);
    doc.text(stamp, pageWidth - MARGIN - w, 0.36);

    doc.setDrawColor(GOLD);
    doc.setLineWidth(0.015);
    doc.line(MARGIN, 0.7, pageWidth - MARGIN, 0.7);

    // Body
    doc.setTextColor(20, 20, 20);
    doc.setFont("times", "normal");
    doc.setFontSize(11);
    const lines = doc.splitTextToSize(letter.letterText, usableWidth) as string[];
    let y = 1.0;
    const bottom = pageHeight - 0.9;
    for (const line of lines) {
      if (y > bottom) {
        addFooter(doc, pageWidth, pageHeight);
        doc.addPage();
        addPageHeader(doc, pageWidth, letter);
        y = 1.0;
      }
      doc.text(line, MARGIN, y);
      y += LINE_HEIGHT;
    }
    addFooter(doc, pageWidth, pageHeight);
  });

  doc.save(`${bundleName}.pdf`);
}
